CredentialSchema:
  blazemeter:
    key:
      type: string
      description: Your API Key Id to connect to the Blazemeter API with
    secret:
      type: string
      description: Your API Key Secret to connect to the Blazemeter API with
    account_id:
      type: int
      description: Your Account ID to connect to the Blazemeter API with
    workspace_id:
      type: int
      description: Your Workspace ID to connect to the Blazemeter API with (Optional). If not given it will pick latest one
Cache:
  blazemeter: Symfony\Component\Cache\Adapter\FilesystemAdapter
