Target:
  Drutiny\BlazeMeter\BlazemeterTarget
CredentialSchema:
  blazemeter:
    key:
      type: string
      description: Your API Key Id to connect to the Blazemeter API with
    secret:
      type: string
      description: Your API Key Secret to connect to the Blazemeter API with
    account_id:
      type: int
      description: Your Account ID to connect to the Blazemeter API with
Cache:
  blazemeter: Symfony\Component\Cache\Adapter\FilesystemAdapter
